### PR TITLE
add Iter2 to prepare for foreach sugar

### PR DESCRIPTION
**Pull request by bobzhang**

### CODE REVIEW

**Comment by bobzhang** [comment]
cc @Guest0x0

**Comment by bobzhang** [comment]
cc @lynzrand do you have any idea why iter2.mbt is red in the coverage report, I am pretty sure I added some test for that file

**Comment by lynzrand** [comment]
> cc @lynzrand do you have any idea why iter2.mbt is red in the coverage report, I am pretty sure I added some test for that file

Investigating 👀

**Comment by lynzrand** [comment]
> cc @lynzrand do you have any idea why iter2.mbt is red in the coverage report, I am pretty sure I added some test for that file

The issue was caused by black box tests of `builtin` not considered to be part of the project itself, thus not using `builtin` itself as coverage provider when compiling `builtin`. A fix is under way.

**Pull request merged**
