### PR TITLE
clean up some deprecated function

### PR DESCRIPTION
**Pull request by Yoorkin**
remove some deprecated function:
- fold_left, fold_right, fold_lefti, fold_righti, ...
- `List::concat_map`, `Ref::ref`, `Iter::tap`
- pop_exn, head_exn, nth_exn, ...
- some util function in test package

### CODE REVIEW

**Comment by bobzhang** [comment]
instead of removing them, shall we use the convention e.g, create a file called deprecated.mbt and put them all together to avoid some breakage. Keep them for a bit longer, e.g, a couple of months?

**Comment by Yoorkin** [comment]
> instead of removing them, shall we use the convention e.g, create a file called deprecated.mbt and put them all together to avoid some breakage. Keep them for a bit longer, e.g, a couple of months?

putting them together in deprecated.mbt looks good to me

**Comment by qazxcdswe123** [comment]
Some may use `@pkg.func`, will this be affected?

**Comment by bobzhang** [comment]
> Some may use @pkg.func, will this be affected if we move them to separated file?

No, it is backwards compatible

**Pull request closed without merging**
