### PR TITLE
feat: add immutable priority queue

### PR DESCRIPTION
**Pull request by Lampese**
## Summary by CodeRabbit

- **New Features**
	- Introduced an ImmutablePriorityQueue library with functionalities such as creating queues, peeking, pushing, and popping elements, and handling empty queues efficiently.
- **Documentation**
	- Added comprehensive documentation for the new ImmutablePriorityQueue library.
- **Refactor**
	- Implemented the priority queue as a pairing heap to optimize various operations.

### CODE REVIEW

**Comment by Lampese** [comment]
@coderabbit pause

**Comment by Lampese** [comment]
@coderabbitai pause

**Comment by Lampese** [comment]
#223 may affect the coverage prompt for newly added content。

**Comment by Lampese** [comment]
@coderabbitai pause

**Comment by bobzhang** [comment]
closed by #261

**Pull request closed without merging**
