### PR TITLE
feat: add sin and cos

### PR DESCRIPTION
**Pull request by Lampese**
References:
- [gcc libgo/go/math/sin.go](https://github.com/gcc-mirror/gcc/blob/ecd2c373720af214f20671f9e7d760548b51ef4a/libgo/go/math/sin.go#L190)
- [gcc lib/go/math/trig_reduce.go](https://github.com/gcc-mirror/gcc/blob/master/libgo/go/math/trig_reduce.go#L29)
- [Rust-libm sin.rs](https://github.com/rust-lang/libm/blob/master/src/math/sin.rs)
- [FreeBSD sin](https://github.com/freebsd/freebsd-src/blob/caccf6d3c008d3c778986734c2705cdae849a877/lib/msun/src/s_sin.c#L51)
- [FreeBSD __kernel_sin](https://github.com/freebsd/freebsd-src/blob/caccf6d3c008d3c778986734c2705cdae849a877/lib/msun/src/k_sin.c#L56)

### CODE REVIEW

**Comment by bobzhang** [comment]
FTR: https://stackoverflow.com/questions/48014858/webassembly-trig-functions-possible some interesting discussions on why sin/cos is not available in wasm

**Comment by bobzhang** [comment]
Why is this closed? We would like to have this as a default implementation

**Comment by Lampese** [comment]
> Why is this closed? We would like to have this as a default implementation @Lampese

Sorry, I seem to have misread the meaning, now that PR has been reopened

**Comment by bobzhang** [comment]
This looks good to me, can you help port more tests from https://github.com/gcc-mirror/gcc/blob/ecd2c373720af214f20671f9e7d760548b51ef4a/libgo/go/math/all_test.go ?

**Pull request merged**
