### PR TITLE
Rename `@assertion` to `@test`

### PR DESCRIPTION
**Pull request by fantix**
Per [discussion](https://github.com/moonbitlang/core/discussions/142), I'm renaming the `@assertion` package to `@test`, and applying the following function renamings *aiming for less typing and readibility*:

| Old Name                   | New Name         | Possible Alternatives         |
|----------------------------|------------------|-------------------------------|
| `@assertion.assert_eq`     | `@test.eq`       | `@test.equal`                 |
| `@assertion.assert_ne`     | `@test.not_eq`   | `@test.ne`, `@test.not_equal` |
| `@assertion.assert_false`  | `@test.is_false` |                               |
| `@assertion.assert_true`   | `@test.is_true`  |                               |
| `@assertion.assert_is`     | `@test.is`       | `@test.physical_eq`           |
| `@assertion.assert_is_not` | `@test.is_not`   | `@test.physical_ne`           |

The possible alternatives are the ones I disliked, but please feel free to comment.

(I'll create another PR to add README and `.git-blame-ignore-revs` to avoid polluting the `git blame`.)

### CODE REVIEW

**Comment by fantix** [comment]
Given that this PR will be ignored in `git blame`, I also ran `moon fmt` for the whole project to keep it clean.

One formatter bug that keeps trying to move comments in a wrong way as shown below:

```console
$ moon version
moon 0.1.0 (4c9971b 2024-03-25)
$ uname -a
Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:31 PST 2024; root:xnu-10063.101.15~2/RELEASE_X86_64 x86_64
$ moon fmt
$ git diff
```
```diff
diff --git a/strconv/int.mbt b/strconv/int.mbt
index c96733d..86dbe30 100644
--- a/strconv/int.mbt
+++ b/strconv/int.mbt
@@ -332,14 +332,20 @@ test "parse_int64_base" {
     ("-10", 8, Ok(-8L)),
     ("57635436545", 8, Ok(0o57635436545L)),
     ("100000000", 8, Ok(1L.lsl(24))),
-    // base 16
     ("10", 16, Ok(16L)),
     ("-123456789abcdef", 16, Ok(-0x123456789abcdefL)),
     ("7fffffffffffffff", 16, Ok(1L.lsl(63) - 1L)),
-    // underscores
     ("-0x_1_2_3_4_5", 0, Ok(-0x12345L)),
     ("0x_1_2_3_4_5", 0, Ok(0x12345L)),
-    ("-_0x12345", 0, Err(syntax_err)),
+    (
+      "-_0x12345",
+      0,
+      Err(
+        // base 16
+        // underscores
+        syntax_err,
+      ),
+    ),
     ("_-0x12345", 0, Err(syntax_err)),
     ("_0x12345", 0, Err(syntax_err)),
     ("0x__12345", 0, Err(syntax_err)),
```

**Comment by bobzhang** [comment]
cc @Yoorkin for the formatter bug

**Comment by bobzhang** [comment]
@fantix this is an aggressive change, can we keep both `@assert` and `@test` for a while and remove `@asset` later

**Comment by fantix** [comment]
> can we keep both `@assert` and `@test` for a while and remove `@asset` later

`@assertion` is now added back as a facade of `@test` in a1dbee7, I'll add deprecation warnings in #164

**Comment by fantix** [comment]
I'm sorry, but I don't think this is working. Time is not in my favor, and it'll be easier for a committer to gate/sort changes like this.

**Pull request closed without merging**
