### PR TITLE
Json & Json5

### PR DESCRIPTION
**Pull request by hackwaly**
This PR port json5 to moonbit

### CODE REVIEW

**Comment by hackwaly** [comment]
error tests are coming later

**Comment by bobzhang** [comment]
can you help fix the CI first?

**Comment by hackwaly** [comment]
It seems typos check can't config to ignore some patterns, we can only put these false positives into whitelist.

**Comment by hackwaly** [comment]
> can you help fix the CI first?

Done. Also the error tests pushed, so coverage check passed.

**Review by bobzhang — APPROVED** [review]

**Pull request merged**
