### PR TITLE
Add to_array and to_string funtions for Iter2

### PR DESCRIPTION
**Pull request by guuzaa**
I've implemented `to_string` and `to_array` functions and the `Show` trait for `Iter2`.

### CODE REVIEW

**Comment by qazxcdswe123** [comment]
```
  let array = [5, 6, 7]
  for k, v in array {
    println("\{k}, \{v}")
  }
  ```

This will do

**Comment by guuzaa** [comment]
In other words, if you'd like to use `for k, v in array`, you need to implement another `iter2` function for your type. However, in many scenarios, it could be tedious to do this for each new type.

**Comment by bobzhang** [comment]
can you split changes to Iter/Iter2 into two PRs?
the interface changes in Iter2 looks good to me, for Iter::enumerate, do you want to return Iter2[Int,A] or Iter[(Int,A)], if performance is not a concern, you may want to return the second for convenience

**Comment by guuzaa** [comment]
This PR only includes changes to Iter2. As for the enumerate function, I'll address it on another PR later.

**Pull request merged**
